# Site settings
title: Notes about Arduino and the Wino Board
email: tobias@abarbanell.de
description: > # this means to ignore newlines until "baseurl:"
  Notes - mainly for myself - about Arduino on various boards, especially 
  the Wino Board (http://www.wino-board.com)
baseurl: "/arduino-wino" # the subpath of your site, e.g. /blog/
url: "http://blog.abarbanell.de" # the base hostname & protocol for your site
twitter_username: tabarbanell
github_username:  abarbanell
google_analytics: UA-5236372-2

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
